"""Curated portfolio records from the 2026-03-07 balloon photo drop."""


def _photo(slug, title, client, category, event_type, width, height, alt):
    return {
        "slug": slug,
        "title": title,
        "client": client,
        "category": category,
        "event_type": event_type,
        "year": "Recent",
        "image": f"{slug}.webp",
        "alt": alt,
        "w": width,
        "h": height,
    }


NEW_BALLOON_PICS_ITEMS = [
    _photo(
        "portfolio-2026-03-07-img-0213",
        "Bright Balloon Character Sculpture",
        "Private event",
        "custom-sculptures",
        "private-events",
        1500,
        2000,
        "Bright yellow and red balloon character sculpture with flower details indoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-0215",
        "Colorful Fiesta Balloon Sculpture",
        "Private event",
        "custom-sculptures",
        "private-events",
        1500,
        2000,
        "Colorful balloon sculpture with pinata-style details and bright streamers",
    ),
    _photo(
        "portfolio-2026-03-07-img-0969",
        "Purple and Gold Organic Backdrop",
        "Private event",
        "picture-perfect-backdrops",
        "private-events",
        1500,
        2000,
        "Purple lavender and gold balloon backdrop with metallic star accents",
    ),
    _photo(
        "portfolio-2026-03-07-img-1263",
        "Blue and Yellow Storefront Arch",
        "Corporate event",
        "balloon-arches",
        "corporate",
        2000,
        1500,
        "Blue and yellow balloon arch installed at an outdoor storefront entrance",
    ),
    _photo(
        "portfolio-2026-03-07-img-1266",
        "Minion Balloon Arch",
        "School event",
        "balloon-arches",
        "schools",
        1500,
        2000,
        "Yellow and blue minion-themed balloon arch installed outdoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-1769",
        "Black Swan Balloon Sculpture",
        "Private event",
        "custom-sculptures",
        "private-events",
        1500,
        2000,
        "Black swan balloon sculpture with metallic balloon base indoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-1771",
        "Health Awareness Balloon Columns",
        "Corporate event",
        "columns",
        "corporate",
        2000,
        1500,
        "Paired blue and copper balloon columns beside a health awareness display",
    ),
    _photo(
        "portfolio-2026-03-07-img-1799",
        "Pink Mom Photo Backdrop",
        "Private event",
        "picture-perfect-backdrops",
        "private-events",
        2000,
        1500,
        "Pink balloon photo backdrop with large mom letters and heart accents",
    ),
    _photo(
        "portfolio-2026-03-07-img-1802",
        "Blue and White Entrance Arch",
        "Corporate event",
        "balloon-arches",
        "corporate",
        1500,
        2000,
        "Blue and white balloon arch framing a business entrance",
    ),
    _photo(
        "portfolio-2026-03-07-img-1807",
        "Rainbow Spiral Event Arch",
        "Community event",
        "balloon-arches",
        "civic-community",
        2000,
        1500,
        "Rainbow balloon spiral arch installed at an outdoor public event",
    ),
    _photo(
        "portfolio-2026-03-07-img-1862",
        "Metallic Fiftieth Backdrop",
        "Private event",
        "picture-perfect-backdrops",
        "private-events",
        1797,
        1103,
        "Metallic gold and silver fiftieth celebration balloon backdrop",
    ),
    _photo(
        "portfolio-2026-03-07-img-1919",
        "Rainbow Outdoor Columns",
        "Community event",
        "columns",
        "civic-community",
        2000,
        1500,
        "Pair of rainbow balloon columns marking an outdoor event walkway",
    ),
    _photo(
        "portfolio-2026-03-07-img-1968",
        "Graduation Star Column",
        "School event",
        "columns",
        "schools",
        1500,
        2000,
        "Graduation balloon column with a star topper and school-color accents",
    ),
    _photo(
        "portfolio-2026-03-07-img-1969",
        "One Hundred Celebration Backdrop",
        "Private event",
        "picture-perfect-backdrops",
        "private-events",
        2000,
        1500,
        "Red gold and black balloon backdrop with large one hundred number balloons",
    ),
    _photo(
        "portfolio-2026-03-07-img-2080",
        "Sixtieth Celebration Backdrop",
        "Private event",
        "picture-perfect-backdrops",
        "private-events",
        1500,
        2000,
        "Copper and silver sixtieth celebration balloon backdrop",
    ),
    _photo(
        "portfolio-2026-03-07-img-2419",
        "Blue and Orange Spiral Sculpture",
        "School event",
        "custom-sculptures",
        "schools",
        1500,
        2000,
        "Tall blue and orange spiral balloon sculpture in a gym",
    ),
    _photo(
        "portfolio-2026-03-07-img-2628",
        "Emerald and Gold Shimmer Wall",
        "Corporate event",
        "picture-perfect-backdrops",
        "corporate",
        2000,
        1500,
        "Emerald black white and gold balloon shimmer-wall backdrop",
    ),
    _photo(
        "portfolio-2026-03-07-img-2634",
        "Progress Pride Balloon Wall",
        "Community event",
        "picture-perfect-backdrops",
        "civic-community",
        2000,
        1500,
        "Progress pride flag balloon wall displayed indoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-2635",
        "Green Restaurant Garland",
        "Corporate event",
        "garlands",
        "corporate",
        2000,
        1500,
        "Green organic balloon garland installed around a restaurant counter",
    ),
    _photo(
        "portfolio-2026-03-07-img-2647",
        "Purple Banquet Centerpieces",
        "Corporate event",
        "centerpieces",
        "corporate",
        2000,
        1500,
        "Purple and white balloon centerpieces arranged across a banquet room",
    ),
    _photo(
        "portfolio-2026-03-07-img-2650",
        "Football Balloon Column",
        "School event",
        "columns",
        "schools",
        1500,
        2000,
        "Purple and white balloon column topped with a football balloon",
    ),
    _photo(
        "portfolio-2026-03-07-img-2651",
        "Basketball Balloon Column",
        "School event",
        "columns",
        "schools",
        1500,
        2000,
        "Purple and white balloon column topped with a basketball balloon",
    ),
    _photo(
        "portfolio-2026-03-07-img-3334",
        "White and Blue Tropical Arch",
        "Private event",
        "balloon-arches",
        "private-events",
        2000,
        1500,
        "White and blue balloon arch with tropical leaf accents",
    ),
    _photo(
        "portfolio-2026-03-07-img-3792",
        "Blue Banquet Balloon Room",
        "Corporate event",
        "centerpieces",
        "corporate",
        2000,
        1500,
        "Blue balloon centerpieces arranged throughout a large banquet room",
    ),
    _photo(
        "portfolio-2026-03-07-img-3793",
        "Green Tree Table Centerpiece",
        "Private event",
        "centerpieces",
        "private-events",
        2000,
        1500,
        "Green balloon tree centerpiece displayed on a table",
    ),
    _photo(
        "portfolio-2026-03-07-img-3800",
        "Orange Tree Table Centerpiece",
        "Private event",
        "centerpieces",
        "private-events",
        1500,
        2000,
        "Orange balloon tree centerpiece displayed on a table",
    ),
    _photo(
        "portfolio-2026-03-07-img-3801",
        "Blue Banquet Balloon Overview",
        "Corporate event",
        "centerpieces",
        "corporate",
        2000,
        1500,
        "Wide banquet-room view with blue balloon centerpieces",
    ),
    _photo(
        "portfolio-2026-03-07-img-3802",
        "Pink Tree Table Centerpiece",
        "Private event",
        "centerpieces",
        "private-events",
        1500,
        2000,
        "Pink and green balloon tree centerpiece displayed on a table",
    ),
    _photo(
        "portfolio-2026-03-07-img-3804",
        "White Tree Table Centerpiece",
        "Private event",
        "centerpieces",
        "private-events",
        2000,
        1500,
        "White and brown balloon tree centerpiece displayed on a table",
    ),
    _photo(
        "portfolio-2026-03-07-img-3809",
        "Blue Anniversary Stage Bouquets",
        "Corporate event",
        "balloon-bouquets",
        "corporate",
        1500,
        2000,
        "Blue and gold balloon bouquets in front of an anniversary stage display",
    ),
    _photo(
        "portfolio-2026-03-07-img-3814",
        "Blue Anniversary Stage Display",
        "Corporate event",
        "picture-perfect-backdrops",
        "corporate",
        2000,
        1500,
        "Large blue and gold anniversary stage balloon display in a banquet room",
    ),
    _photo(
        "portfolio-2026-03-07-img-3820",
        "Blue Balloon Banquet Centerpieces",
        "Corporate event",
        "centerpieces",
        "corporate",
        2000,
        1500,
        "Blue balloon centerpieces arranged on banquet tables",
    ),
    _photo(
        "portfolio-2026-03-07-img-3948",
        "Outdoor Rainbow Entrance Arch",
        "Community event",
        "balloon-arches",
        "civic-community",
        2000,
        1500,
        "Rainbow balloon arch installed at an outdoor entrance",
    ),
    _photo(
        "portfolio-2026-03-07-img-4166",
        "White Balloon Table Centerpieces",
        "Private event",
        "centerpieces",
        "private-events",
        2000,
        1935,
        "White helium balloon table centerpieces with greenery accents",
    ),
    _photo(
        "portfolio-2026-03-07-img-4220",
        "Western Balloon Character Column",
        "Community event",
        "custom-sculptures",
        "civic-community",
        1500,
        2000,
        "Western-themed balloon character column installed outdoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-4225-jpeg",
        "Balloon Train Installation",
        "Venue install",
        "custom-sculptures",
        "venues-public",
        2000,
        1093,
        "Large train-themed balloon installation with blue backdrop",
    ),
    _photo(
        "portfolio-2026-03-07-img-4225-jpg",
        "Autumn Outdoor Columns",
        "Community event",
        "columns",
        "civic-community",
        2000,
        1500,
        "Autumn-color balloon columns installed at an outdoor public event",
    ),
    _photo(
        "portfolio-2026-03-07-img-4239",
        "Blue and Silver Balloon Wall",
        "Corporate event",
        "picture-perfect-backdrops",
        "corporate",
        2000,
        2000,
        "Blue silver and pearl balloon wall with a geometric pattern",
    ),
    _photo(
        "portfolio-2026-03-07-img-4341",
        "Hot Air Balloon Sculpture",
        "Private event",
        "custom-sculptures",
        "private-events",
        1500,
        2000,
        "Red white and blue hot air balloon sculpture indoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-4345",
        "White and Green Event Dome",
        "Corporate event",
        "custom-sculptures",
        "corporate",
        1500,
        2000,
        "Large white and green balloon dome installation in an event room",
    ),
    _photo(
        "portfolio-2026-03-07-img-4395",
        "Rainbow Stage Arches",
        "Community event",
        "balloon-arches",
        "civic-community",
        2000,
        1500,
        "Layered rainbow balloon arches installed on a stage",
    ),
    _photo(
        "portfolio-2026-03-07-img-4573",
        "Black and White Venue Garland",
        "Venue install",
        "garlands",
        "venues-public",
        2000,
        1500,
        "Black and white organic balloon garland installed above a venue counter",
    ),
    _photo(
        "portfolio-2026-03-07-img-5346",
        "Blue Carriage Balloon Sculpture",
        "Private event",
        "custom-sculptures",
        "private-events",
        2000,
        1436,
        "Blue carriage balloon sculpture with white wheel details",
    ),
    _photo(
        "portfolio-2026-03-07-img-5655",
        "Casino Ceiling Balloon Garland",
        "Venue install",
        "garlands",
        "venues-public",
        2000,
        1500,
        "Casino-themed balloon garland suspended near a venue ceiling",
    ),
    _photo(
        "portfolio-2026-03-07-img-5680",
        "Casino Entrance Balloon Garland",
        "Venue install",
        "garlands",
        "venues-public",
        2000,
        1500,
        "Casino-themed black red and blush balloon garland at an entrance",
    ),
    _photo(
        "portfolio-2026-03-07-img-7187",
        "Purple Balloon Flower Bouquet",
        "Private event",
        "balloon-bouquets",
        "private-events",
        1500,
        2000,
        "Purple and teal balloon flower bouquet on a wall",
    ),
    _photo(
        "portfolio-2026-03-07-img-7743",
        "Greenery Photo Backdrop",
        "Corporate event",
        "picture-perfect-backdrops",
        "corporate",
        2000,
        1500,
        "Greenery and white balloon photo backdrop against a brick wall",
    ),
    _photo(
        "portfolio-2026-03-07-img-7782",
        "Purple Hallway Garland",
        "Corporate event",
        "garlands",
        "corporate",
        1500,
        2000,
        "Purple white and black balloon garland installed along a hallway",
    ),
    _photo(
        "portfolio-2026-03-07-img-7783",
        "Purple Venue Garland",
        "Corporate event",
        "garlands",
        "corporate",
        2000,
        1500,
        "Purple and black balloon garland wrapping a venue railing",
    ),
    _photo(
        "portfolio-2026-03-07-img-8362",
        "Mermaid Photo Backdrop",
        "Private event",
        "picture-perfect-backdrops",
        "private-events",
        1500,
        2000,
        "Mermaid-themed balloon photo backdrop installed outdoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-8439",
        "Gold and White Table Garland",
        "Private event",
        "garlands",
        "private-events",
        2000,
        1500,
        "Gold white and champagne balloon garland above a long table",
    ),
    _photo(
        "portfolio-2026-03-07-img-8440",
        "Gold Fiftieth Number Columns",
        "Private event",
        "columns",
        "private-events",
        2000,
        1500,
        "Gold fiftieth number balloons with champagne balloon column bases",
    ),
    _photo(
        "portfolio-2026-03-07-img-8441",
        "Champagne Fiftieth Number Columns",
        "Private event",
        "columns",
        "private-events",
        1500,
        2000,
        "Champagne and gold fiftieth celebration balloon columns near a fireplace",
    ),
    _photo(
        "portfolio-2026-03-07-img-8456",
        "Blue Balloon Car Sculpture Front",
        "Community event",
        "custom-sculptures",
        "civic-community",
        2000,
        1500,
        "Large blue balloon car sculpture installed outdoors under a canopy",
    ),
    _photo(
        "portfolio-2026-03-07-img-8457",
        "Blue Balloon Car Sculpture Rear",
        "Community event",
        "custom-sculptures",
        "civic-community",
        2000,
        1500,
        "Rear view of a large blue balloon car sculpture outdoors",
    ),
    _photo(
        "portfolio-2026-03-07-img-8625",
        "Clear Balloon Walkway Garland",
        "Corporate event",
        "garlands",
        "corporate",
        2000,
        1500,
        "Clear balloon garland installed along an indoor walkway",
    ),
    _photo(
        "portfolio-2026-03-07-img-9055",
        "Rainbow Balloon Wall",
        "Community event",
        "picture-perfect-backdrops",
        "civic-community",
        2000,
        1500,
        "Rainbow balloon wall with white cloud-like base balloons",
    ),
    _photo(
        "portfolio-2026-03-07-img-9061",
        "Green and White Celebration Arch",
        "Private event",
        "balloon-arches",
        "private-events",
        2000,
        1500,
        "Green white and gold balloon arch framing a celebration table",
    ),
    _photo(
        "portfolio-2026-03-07-img-9269",
        "Rainbow Heart Arch Walkway",
        "Community event",
        "balloon-arches",
        "civic-community",
        2000,
        1500,
        "Outdoor walkway lined with rainbow heart balloon arches",
    ),
]


NEW_BALLOON_PICS_DISPLAY_ORDER = [item["slug"] for item in NEW_BALLOON_PICS_ITEMS]

NEW_BALLOON_PICS_REEL_META = {
    item["slug"]: {"w": item["w"], "h": item["h"]} for item in NEW_BALLOON_PICS_ITEMS
}
